# Spreading Knowledge, One Infographic at a Time {#Infographic-Database} <!--good!-->

#### Keywords

infographic, database, integrity, social media, knowledge, facts <!--add tech keywords-->

## The Underused Value of Research <!--good headings!-->

Have you ever scrolled through your news feed to find an infographic displaying a few simple statistics that blow your mind? 
Social and political issues are often highlighted in this manner, for example a short video clip outlining information about women in the work place or average wage by ethnicity. 
These tidbits of tangible information shared in a simple and clean way are incredibly informative and eye-opening. <!--example?-->
If you could, wouldn't you want to have access to a tool that produces custom visualizations with valuable information on almost any topic you can imagine? <!--If this were about food, would you want to make visualizations of the ingredients, or of a prepared dish?-->

Governments across the world collect and publish large amounts of data every year, typically obtained through censuses or other pointed studies. 
These data is readily available online, but often comes in the form of hefty files or long-winded reports. <!--With the current administration, not as available as it used to be!-->
Other bodies, such as business or non-profit organizations, also collect and publish valuable information that could positively impact education or decision making. 
Unfortunately, the insights from these datasets often don't make it past page three of a tab buried deep within an unassuming website.

## Research and Media Collide

I would like to take advantage of these datasets to produce an educational visualization database and search tool. 
The product will routinely read and process data posted by verifiable research bodies. 
Each data set will be tagged by topic using natural language processing, and then aggregated with data processed from other sources that covers the same subject. <!--This isn't about data as much as the topics people are interested in.-->
A variety of visualization styles or templates, including different types of charts, graphs, and phrases combined to form short video clips, pictures, or reports, will be constructed.

When users enter a search term into the tool, the system queries its database and returns results based on relevancy, credibility and popularity. <!--Chicken and egg. Order is imposed by people's queries, not by a latent structure in the data.-->
The data sets returned by the query are matched to a visualization template using a set of best-practice rules and machine learning algorithms, and finally displayed to the user. <!--The ML will need to be supervised, hence Chicken and Egg.-->
From there, the user can interact with the search results in a number of ways, such as: scrolling through search results, viewing raw data sets, viewing information about the source of data, customizing visualization templates, and finally saving an infographic visualization to their desktop or posting to social media. <!--Information overload?-->

The tool would accumulate data covering a broad range of topics both serious and trivial, making it useful for boardrooms, classrooms, and living rooms alike. 
In addition to interacting with the tool as a public user, stakeholders such as governments, businesses, and nonprofits may submit datasets for consideration to be added to the database, or liscence the tool to directly process and visualize data internal to their organizations. <!--Should you assume order or chaos in the data?-->

## Considerations: Separating Fact and Fallacy

There are a major considerations that will need to be solved. 
As effective an instructive tool as infographics may be, they are notorious for showing half-truths, using data to skew ideas, or citing unreliable sources. <!--social science?-->
Each of these problems will need to be assessed and protected against to ensure the truth of the data is conveyed most accurately. <!--just eda?-->
This means verifying the source and scope of raw data, ensuring visualization algorithms uphold a standard of quality, as well as recognizing the stigmas and limitations attached to infographics as a visualization medium. <!--explain "stigmas"-->
In addition, users will need to be protected from polling data incorrectly or selecting inappropriate visualization templates when generating infographics. 
Algorithms to pull and process data must be safeguarded against accidental misuse or error. <!--how, if this is on the user side?-->
There is considerable work to be done to ensure the product is both effective and truthful.

That being said, the product shows great potential at this preliminary stage. 
The tool will have the ability to be easily integrated with both formal reports and social media newsfeeds, or used directly in educational institutions and workplaces alike. 
In addition to its entertainment value, the product provides an educational solution for people of any walk of life to visualize the reality of important topics such as politics or economics, which in turn allows truthful knowledge to disseminate through the greater public. <!--laudable goal!-->
This knowledge, as a result, has the potential to positively impact personal and public decision making.

