# Mega Storms: Real-Time Optimization of Resource Allocation in Large Storms {#storm-resource-optimization}

#### Keywords

storms, resource allocation, first responders, displacement, government, social media, optimization, real-time

## The Storm Front.

Nature is at times anything but gentle and although we too have the power to raise and level cities, people are frequently left helpless during and after massive storms such as hurricanes, tornadoes and earthquakes. While emergency response systems have improved dramatically in the past century, people still endure great risk during storm events regardless of preparation or foresight. The advancements in connectivity over the past couple decades, however, may stand to develop storm response systems by optimizing the allocation of emergency responders and supplies, which can ultimately save lives.

## The Eye of the Storm.

To what extent can connectivity improve storm safety and relief efforts? We will only know for certain when these types of systems are used first-hand to combat the effects of a natural disaster, but upon first glance I believe the impact could be staggering.

The proposed solution uses an aggregation of real-time social media and mobile device data to track the location and status of people during a storm in combination with meteorological data forecasting a storm's movement, characteristics and strength. The system is best implemented as a government-funded tool that, in conjunction with social media services and cellular data providers, collects user data during inclement weather. In addition to gathering data, the tool pushes notifications to citizens' cellular devices, through an embedded operating system functionality, for example, which allows people to check in with authorities as safe or request emergency assistance. This information, combined with real-time population density and movement data from social media posts or cellular device locations, and storm path data from meterological prediction algorithms, will be aggregated and provided to decision makers. These insights will provide sufficient information to effectively allocate available resources, including rescue workers, medical supplies, food, water and shelter, on a real-time basis. The result is an emergency response system that can have an impactful presense during both the onset and peak of a storm, in addition to the days, weeks, or months of repairs that take place afterwards.

## The Aftermath.

There are several roadblocks that immediately restrict this solution. 

Firstly, information privacy will be a concern of impacted citizens, as the system may need to collect data without informed consent. In this respect, there is a tradeoff between storing personal information regarding the location of individuals, which may be helpful in reuniting families after a storm, versus cleaning personal information from collected data to protect the privacy rights of individuals. While more descriptive data stands to improve the system's accuracy and efficiency, even the barest data set, devoid of any personal information, may still have a significant impact on the ability for municipalities to dispatch rescue workers and other resources. In addition, there is potential for individual location and status information to be collected without breaching personal privacy, for example by using natural language process algorithms to interpret public social media posts relevant to the storm.

A second barrier to entry is the cost and participation required to implement the solution. The system requires cooperation between many large stakeholders: politicians, emergency responders, cellular network providers, relevant social media companies, and meterorologists, for example, in addition to requiring a fair amount of physical infrastructure in order to operate. In this respect, there is a minimum about of buy-in required from these stakeholders in order for the system to be successful: in other words, the idea needs to be pursued actively by multiple parties or the implementation will not work. The opportunity to improve on response systems, however, is immense and worthwhile for all parties to seriously consider. Stakeholders may also find the system easier to justify or gain support for by implementing it incrementally, for example focusing first on a hazard reporting system before moving to emergency supply logisitics and subsequently an emergency responder optimization system.

Finally, the physical infrastructure of the system will need to be robust to power outages, cell tower damage and other utility interruptions that may occur during a storm.

If implemented correctly, the tool has the power to reduce the havoc a storm may reap on an area and assist communities in developing best practices and foresight to protect against future storms. In its full implementation, the system can help a city by minimizing lives lost, getting the right supplies into the hands that need them at the right time, and allowing citizens, governments and corporations to stand together in a united front.
